# Lab 1 – Basic NumPy Operations

## Part A

### Importing Numpy for Notebook

In [5]:
import numpy as np

### Array starting from 1 and ends at 20 with incremental by 3

In [2]:
arr1 = np.arange(1, 21, 3)
print(arr1)

[ 1  4  7 10 13 16 19]


### Array of shape 3 with random numbers between 0 and 1

In [3]:
arr2 = np.random.rand(3)
print(arr2)

[0.31173744 0.85929433 0.48617459]


### Array of 2 D with slicing to get first two rows and last two rows

In [4]:
Array2D=np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
arr3_f_slice=Array2D[:2,:]
arr4_l_slice=Array2D[-2:,:]
print(arr3_f_slice)
print(arr4_l_slice)

[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


### Array of 2x2 and stack the elements vertical, horizontal and split the array to smaller ones

In [6]:
Array2x2=np.array([[10, 20], [42, 17]])
arr5_vstack=np.vstack([Array2x2, Array2x2])
arr6_hstack=np.hstack([Array2x2, Array2x2])
print(arr5_vstack)
print(arr6_hstack)

[[10 20]
 [42 17]
 [10 20]
 [42 17]]
[[10 20 10 20]
 [42 17 42 17]]


### Multiply the 3x3 matrix X by the 3x2 matrix Y. Yes, Multiplying two matrices is possible because the number of rows are equal

In [ ]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

arr_multiply = np.dot(X, Y)
print(arr_multiply)

[[70 28]
 [70 30]
 [60 26]]


### Create two arrays, find shape and dimensions, then reshape to (3,1)

In [16]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)

x_reshaped = x.reshape(3, 1)
y_reshaped = y.reshape(3, 1)

print("Reshaped x (3,1):\n", x_reshaped)
print("Shape of reshaped x:", x_reshaped.shape)
print("Number of dimensions of reshaped x:", x_reshaped.ndim)
print("Reshaped y (3,1):\n", y_reshaped)
print("Shape of reshaped y:", y_reshaped.shape)
print("Number of dimensions of reshaped y:", y_reshaped.ndim)

Shape of x: (3,)
Number of dimensions of x: 1
Reshaped x (3,1):
 [[ 2]
 [-1]
 [-8]]
Shape of reshaped x: (3, 1)
Number of dimensions of reshaped x: 2
Reshaped y (3,1):
 [[ 3]
 [ 1]
 [-2]]
Shape of reshaped y: (3, 1)
Number of dimensions of reshaped y: 2


### Broadcasting: subtraction and multiplication on a 3x3 matrix

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 20, 30])

sub_result = A - B
mul_result = A * B

print("Broadcasted subtraction (A - B):\n", sub_result)
print("Broadcasted multiplication (A * B):\n", mul_result)

Broadcasted subtraction (A - B):
 [[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]
Broadcasted multiplication (A * B):
 [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


## Graph Overview

- Line graph: Shows how a value changes continuously over time or another variable.
- Bar chart: Compares different categories using rectangular bars of varying heights.
- Scatter plot: Displays the relationship between two variables by plotting points.
- Histogram: Shows the distribution of numerical data by grouping values into ranges.
- Pie chart: Represents parts of a whole as slices of a circle.
- Box plot: Summarizes the spread and central tendency of a dataset using quartiles.
- Heatmap: Visualizes data values with colors to show patterns or intensity across a matrix.

# Part B

### Solving two linear equations by using matrices and checking the number of solutions

In [13]:
# System 1
A1 = np.array([[2, 3, -4], [1, -4, 0]])
b1 = np.array([6, 8])
Rank_A1 = np.linalg.matrix_rank(A1)
Rank_A1_b1 = np.linalg.matrix_rank(np.hstack([A1, b1.reshape(-1, 1)]))
if Rank_A1 == Rank_A1_b1:
    print("System 1 has infinitely many solutions because rank(A1) = rank([A|b]).")
else:
        print("System 1 has no solutions because rank(A1) != rank([A|b]).")

# Solve using least squares / pseudo-inverse because system is underdetermined
x1 = np.linalg.pinv(A1) @ b1
x2 = np.linalg.pinv(A1) @ b1
print("Value of x1:", x1[0])
print("Value of x2:", x2[1])

# System 2

A2 = np.array([[3, -4, 5],
               [-1, 2, -4]])
b2 = np.array([10, 8])

Rank_A2 = np.linalg.matrix_rank(A2)
Rank_A2_b2 = np.linalg.matrix_rank(np.hstack([A2, b2.reshape(-1, 1)]))
if Rank_A2 == Rank_A2_b2:
    print("System 2 has infinitely many solutions because rank(A2) = rank([A|b]).")
else:
    print("System 2 has no solutions because rank(A2) != rank([A|b]).")


System 1 has infinitely many solutions because rank(A1) = rank([A|b]).
Value of x1: 1.6692111959287526
Value of x2: -1.5826972010178109
System 2 has infinitely many solutions because rank(A2) = rank([A|b]).
